site_name: Maghreb Events Wiki
site_description: Documentation for the Maghreb Events project
repo_url: https://github.com/Maghreb-events-website/mk-docs-wiki-demo

theme:
  name: material

nav:
  - Home: index.md
  - Getting Started: getting-started.md