site_name: Maghreb Wiki
site_description: Documentation for Maghreb vACC
site_url: https://maghreb-events-website.github.io/mk-docs-wiki-demo/

theme:
  name: material

  logo: assets/logo.png
  favicon: assets/logo.png

  palette:
    - scheme: slate
      primary: black
      accent: red

      toggle:
        icon: material/brightness-4
        name: Switch theme

  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.instant
    - search.highlight
    - content.code.copy

extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Guide:
      - Setup: guide/setup.md
      - Deployment: guide/deployment.md
  - API: api.md